### ISSUE TITLE
Tests / build broken by cohttp 2.5.3

### ISSUE THREAD

**Issue by sternenseemann** [inhabitedtype/ocaml-webmachine#106]
Test suite output:

```
  .......F..............................
  ==============================================================================
  Failure: test logic:7:head method not allowed
  
  405 from head method now allowed
  expected: <none> but got: GET,POST,PUT
  ------------------------------------------------------------------------------
  Ran: 38 tests in: 0.03 seconds.
  FAILED: Cases: 38 Tried: 38 Errors: 0 Failures: 1 Skip:  0 Todo: 0 Timeouts: 0.
```

Builds correctly with cohttp 2.5.1 and otherwise unchanged environment. I suspect the breaking change was introduced in cohttp 2.5.2. Happens on webmachine 0.6.1 and 0.6.2.

**Comment by sternenseemann** [comment]
Seems like the change breaking `webmachine` has been reverted in 2.5.3: <https://github.com/mirage/ocaml-cohttp/releases/tag/v2.5.4>.

**Comment by seliopou** [comment]
It looks like `cohttp.2.5.2` is uninstallable, and it's since moved forward to version `cohttop.2.5.4` which CI is using, and is passing with it. I don't think there's anything to do about this at this point.

Thanks for reporting.
