### ISSUE TITLE
How to return HTTP 201 (created) after a POST?

### ISSUE THREAD

**Issue by slegrand45** [inhabitedtype/ocaml-webmachine#32]
Hello,

It seems that the only path which can return a 201 is from P11 state. And in https://raw.githubusercontent.com/wiki/webmachine/webmachine/images/http-headers-status-v3.png we can see that there is a new resource check from this state. But how to implement this with webmachine? Currently, the v3p11 method only checks if a location header exists.

Thanks.

**Comment by seliopou** [comment]
Hey there, the new resource check amounts to checking whether a `Location` response header exists, as you observed. Without a `Location` header, a `201` would not conform to the HTTP spec. You should set the location header in the `process_post` method or in a handler returned by `content_types_provided` when handling `PUT` requests.

Note that there is a subgraph of the decision diagram that was not implemented as part of the initial release that may be relevant to the use-case you're contemplating with this question. That part is related to allowing `POST` requests to non-existent resources. You can see some stub code for the handlers commented out [here](https://github.com/inhabitedtype/ocaml-webmachine/blob/master/lib/webmachine.ml#L243-L251). This should be supported by the library, but wasn't part of the initial release for the sake of expediency.

**Comment by slegrand45** [comment]
Thanks for your answer. So i tried to set a location header but now i get a 303 and not a 201 when i send a POST request. Without setting the location header i get a 200. Basically, my code is similar to that:

```ocaml
class id = object(self)
  inherit [Cohttp_lwt_body.t] Wm.resource

  method allowed_methods rd =
    Wm.continue [`GET; `POST; `PUT; `DELETE] rd

  method content_types_provided rd =
    Wm.continue [
      ("application/json", self#to_json);
    ] rd

  method content_types_accepted rd =
    Wm.continue [
      ("application/json", (Wm.continue true));
    ] rd

  method process_post rd =
    self#post rd >>= Wm.continue true

  method private post rd = 
    Cohttp_lwt_body.to_string rd.Wm.Rd.req_body >>= (
      fun v -> ... (* do stuff *)
           let h = rd.Wm.Rd.resp_headers in
           let h = Cohttp.Header.add_unless_exists h "location" "/item/id/xxx" in
           Lwt.return { rd with Wm.Rd.resp_body = `String json; resp_headers = h }
    )

  method private to_json rd =
         ...
         Wm.continue (`String json) rd

end
```

**Comment by seliopou** [comment]
I see. This is indeed a bug. Essentially, the code cannot distinguish between the "redirect" case and the "resource created" case. The solution is to add a field to the `Rd.t` type indicating whether or not this is a redirect or not. The module should most likely include a `redirect` helper function to set the `Location` header and flip the bit as well.

**Comment by slegrand45** [comment]
Ok, thanks. I will for now use the 200 code return. By the way, i also don't succeed to make a PUT request. I will open a new PR for that.
