### ISSUE TITLE
Implement missing POST functionality

### ISSUE THREAD

**Issue by tmcgilchrist** [inhabitedtype/ocaml-webmachine#50]
Just a heads up I'm going part way through implementing this.

Basically I'm going to follow how erlang web machine does it.

**Comment by tmcgilchrist** [comment]
FYI https://github.com/inhabitedtype/ocaml-webmachine/commit/6ff58d817e065eff5eefd3980880c1a26c41a17c

**Comment by seliopou** [comment]
Cool! Send a pull request when you think it's ready. I'm releasing 0.3.1 right now and will then merge your cache headers PR.

**Comment by seliopou** [comment]
@tmcgilchrist Do you mind if I use some or all of the patch you referenced above?

**Comment by tmcgilchrist** [comment]
Not at all. Go for it.

**Comment by hannesm** [comment]
this has been merged as part of #96 and part of the 0.7.0 release. I think this issue can be safely closed.
