### ISSUE TITLE
Corrupted PUT functionality in crud_lwt example

### ISSUE THREAD

**Issue by pkel** [inhabitedtype/ocaml-webmachine#54]
A PUT on _localhost:8080/item/2_ changes all items put item 2. Change in [crud_lwt.ml](https://github.com/inhabitedtype/ocaml-webmachine/blob/master/examples/crud_lwt.ml) on lines 74 and 75
```ocaml
          then begin found := true; (id', e') end
          else (id', e))
```
to
```ocaml
          then begin found := true; (id', e) end
          else (id', e'))
```
to solve the issue.

**Comment by seliopou** [comment]
Fixed, thanks!
