### ISSUE TITLE
Cannot build from source: Cohttp_async_io is unbounded (OS X 10.11.6)

### ISSUE THREAD

**Issue by aaronwinter** [inhabitedtype/ocaml-webmachine#75]
When trying to build from sources with tests enabled:

```
./configure --enable-examples
make clean && make
```

yields the following error:

Zoom: `Error: Unbound module Cohttp_async_io`

context:

```
File "examples/hello_async.ml", line 1, characters 5-13:
Warning 3: deprecated: module Core.Std
[since 2017-02] Use Core. The Std sub-module is no longer needed
File "examples/hello_async.ml", line 2, characters 5-14:
Warning 3: deprecated: module Async.Std
[since 2017-02] use Async. The Std sub-module is no longer needed
File "examples/hello_async.ml", line 5, characters 5-20:
Error: Unbound module Cohttp_async_io
Hint: Did you mean Cohttp_async?
Command exited with code 2.
```

even after I run `opam install --deps-only webmachine`:

```
$ opam install --deps-only webmachine

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[webmachine] /Users/erwan/ocaml-webmachine/ already up-to-date
```

My `uname -a` : 

```
Darwin bastiat.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

My `ocaml --version`:

```
 The OCaml toplevel, version 4.04.2
```

I obtain the same error when install from opam (via `opam install webmachine`).

**Comment by seliopou** [comment]
Thanks for reporting this, I will look into it this weekend.

**Comment by rgrinberg** [comment]
I think Cohttp 0.99 changed this to Cohttp_async.Io (when we moved it to aliases). I did a rev dep search for possible breakage of this but i think the depopts made me miss this case..

**Comment by tmcgilchrist** [comment]
I ran into the same problem while porting the build across to jbuilder. I
can do a small fix for them.

**Comment by seliopou** [comment]
This should be fixed by the patch from @tmcgilchrist.

**Comment by aaronwinter** [comment]
@tmcgilchrist thanks for the swift action!
