### ISSUE TITLE
Implement parser for HTTP date format

### ISSUE THREAD

**Issue by seliopou** [inhabitedtype/ocaml-webmachine#79]
See the specification in [RFC7231§7.1.1.1](https://tools.ietf.org/html/rfc7231#section-7.1.1.1). [Angstrom](https://github.com/inhabitedtype/angstrom) may help in this effort, or maybe something hand-rolled would work just as well.

**Comment by tmcgilchrist** [comment]
Forgive the naive question but is there a preferred way to get the current time?
Is the standard library function `val time : unit -> float` good enough (suspect not) or should it be something that is functorized into webmachine? e.g. `Webmachine.Make(Id, TimeSource)`

**Comment by seliopou** [comment]
I think the latter's more likely. I haven't checked but I imagine that `time` is from libc and in the end has to call `gettimeofday` or something related. So not portable to mirage AFAKI.

**Comment by samoht** [comment]
Seems that @dinosaure already implemented this for parsing dates in emails: https://github.com/oklm-wsh/MrMime/blob/master/lib/mrMime_date.mli

Would be probably useful to have that as an stand-alone package and library.
